<?php

$initialHomebaseCourseInfo = array(
	'sections' => array(

		//Military Culture and Intro Courses
		"Collapse0"  => array(
			3043,
			3152,
			3050,
			3022,
			3049,
			3048,
			3021,
			3070,
			2669,
			2771
		),
		// PTSD Courses
		"Collapse1"  => array(
			3035,
			3029,
			3034,
			3051,
			3045,
			3025,
			3031,
			3032,
			3042,
			3024,
			2669,
			2771
		),
		// TBI Courses
		"Collapse2"  => array(
			3035,
			3051,
			3030,
			3180,
			2669,
			2771
		),
		// Substance Use Courses
		"Collapse3"  => array(
			3045,
			3038,
			3070,
			2669,
			2771
		),
		// "Additional Trauma and Treatment Courses"
		"Collapse4"  => array(
			// 3023,
			3027,
			//3028,
			3033,
			3036,
			3037,
            3038,
			3039,
			3040,
			3041,
			3045,
			3046,
			3070,
			3072,
			2669,
			2771
		),
		// "Military Family Courses"
		"Collapse5"  => array(
			3023,
			3025,
			3026,
			3027,
			3028,
			3044,
			3047,
			3071,
			2771
		)
	),

	'allCourses' => array(
		2669 => array('title' => "Serving Those Who Have Served: Practical Approaches to Addressing the Invisible Wounds of War in Service Members and Post-9\/11 Veterans - HEALTH CARE PROFESSIONALS",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		2771 => array('title' => "Serving Those Who Have Served: Practical Approaches to Addressing the Invisible Wounds of War in Service Members and Post-9\/11  Veterans - FIRST RESPONDERS",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3021 =>  array('title' => "The Challenges of Coming Home After War: What Providers Need to Know",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3022 => array('title' => "Reintegration Issues From the Veterans Perspective: Overcoming the Stigma of Seeking Help",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3023 => array('title' => "When One Family Member Serves the Entire Family Serves",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3024 => array('title' => "Recognizing PTSD and Co-Morbidities",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3025 => array('title' => "Keeping Military Families Emotionally Strong: Couples Therapy for PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3026 => array('title' => "Challenges Facing Other Family Members When a Veteran has PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3027 => array('title' => "Supporting Resilience in Military Connected Children: The PACT Model",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3028 => array('title' => "Impact of Combat-Related Injury, Illness, and Death on Military Children and Families",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3029 => array('title' => "Clinical Practice Guidelines and Resources for PTSD Treatment",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3030 => array('title' => "Traumatic Brain Injury",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3031 => array('title' => "Prolonged Exposure and Virtual Reality Therapy for PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3032 => array('title' => "Psychopharmacology of PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3033 => array('title' => "Military Sexual Trauma",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3034 => array('title' => "Cognitive Processing Therapy for PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3035 => array('title' => "Challenges of Treating Co-Morbid PTSD and TBI",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3036 => array('title' => "Recognizing Suicide Risk in Returning Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3037 => array('title' => "Sleep Issues in Returning Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3038 => array('title' => "Substance Abuse",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3039 => array('title' => "Aggression and Domestic Violence",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3040 => array('title' => "Managing Grief and Loss in Returning Veterans and Families",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3041 => array('title' => "Pain Issues in Returning Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3042 => array('title' => "PTSD Diagnosis and DSM-V",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3043 => array('title' => "Is there an app for that?",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3044 => array('title' => "Staying Strong: Helping Families and Schools Build Resilience in Military-Connected Children",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3045 => array('title' => "Clinical Case Conference - When Substance Abuse and PTSD Collide",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3046 => array('title' => "Reproductive Mental Health Care in Younger and Older Female Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3047 => array('title' => "Clinical Case Conference - When a Parent has PTSD: Restoring Resilience in Parents and Their Children",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3048 => array('title' => "Student Veterans Health: What College Health Professionals and Faculty Need to Know",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3049 => array('title' => "Service Dogs, Acupuncture, Psychotherapy, and More: What's the Evidence and What's Evidence-based",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3050 => array('title' => "Physical Health and Mental Health Following Deployment",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3051 => array('title' => "Clinical Case Conference - Recognizing and Treating Mild TBI and PTSD",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3070 => array('title' => "Introducing VetChange:  An Online Intervention for Veterans with Problem Drinking and PTSD Symptoms",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3071 => array('title' => "Suicide Postvention: Survivor Care for Families of Service Members and Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3072 => array('title' => "Opioid Use Disorders: Considerations in Medication Assisted Treatments of Military Veterans",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3152 => array('title' => "Military Culture",
			'blue_box_text' => "", 'disabled' => false, 'video_embed_link' => ''),
		3180 => array('title' => "Mild Traumatic Brain Injury: Acute Management, Differential Diagnosis, Treatment, and Rehabilitation (April 2017)",
			'blue_box_text' => "If you are interested in taking this course when it becomes available again, please email Emma Morrison at emorrison4@partners.org.", 'disabled' => true, 'video_embed_link' => 'http://www.youtube.com/watch?v=XHCtZJw0WU0'),
	),

	'audiences' => array(
		2669 => array("Professionals"),
		2771 => array("Responders"),
		3021 => array("Professionals", "Community", "Responders", "Families"),
		3022 => array("Professionals", "Community", "Responders", "Families"),
		3023 => array("Community", "Families", "Responders", "Professionals"),
		3024 => array("Professionals", "Community", "Responders", "Families"),
		3025 => array("Professionals", "Community", "Responders", "Families"),
		3026 => array("Professionals", "Community", "Responders", "Families"),
		3027 => array("Responders", "Professionals"),
		3028 => array("Professionals", "Community", "Responders", "Families"),
		3029 => array("Professionals", "Community", "Responders", "Families"),
		3030 => array("Professionals", "Community", "Responders"),
		3031 => array("Professionals"),
		3032 => array("Professionals"),
		3033 => array("Professionals", "Community", "Responders", "Families"),
		3034 => array("Professionals"),
		3035 => array("Professionals", "Community", "Responders", "Families"),
		3036 => array("Professionals", "Community", "Responders", "Families"),
		3037 => array("Professionals", "Community", "Responders", "Families"),
		3038 => array("Professionals", "Responders", "Families", "Community",),
		3039 => array("Professionals", "Community", "Responders", "Families"),
		3040 => array("Professionals", "Community", "Responders", "Families"),
		3041 => array("Professionals", "Community", "Responders", "Families"),
		3042 => array("Professionals"),
		3043 => array("Professionals", "Community", "Responders", "Families"),
		3044 => array("Professionals", "Community", "Responders", "Families"),
		3045 => array("Professionals"),
		3046 => array("Professionals"),
		3047 => array("Professionals"),
		3048 => array("Professionals", "Community", "Responders", "Families"),
		3049 => array("Professionals", "Community", "Responders", "Families"),
		3050 => array("Professionals", "Community", "Responders", "Families"),
		3051 => array("Professionals"),
		3070 => array("Professionals"),
		3071 => array("Community", "Families", "Responders", "Professionals"),
		3072 => array("Professionals"),
		3152 => array("Professionals", "Community", "Responders", "Families"),
		3180 => array("Professionals"),
	),
	'featuredItemsInfo' => array(
		3023,
		3027,
		3035,
		3038,
		3040,
		3070,
		3071,
		3072,
		3152
	)
);
